### ISSUE TITLE
No login for Frankfurt University possible

### ISSUE THREAD

**Issue by boredland** [MyGrades/mygrades-app#10]
It seems the login doesn't work anymore. Let me know if I could help debugging that.

**Comment by jonastheis** [comment]
That would be awesome. Do you need some instructions on how to debug it? 
I assume there's just a small change in the HTML. Here's the mapping rule for it: https://github.com/MyGrades/mygrades-server/blob/master/database/seeds/universities/FHFrankfurt.php

It seems like I created the mapping a while ago and it's too specific, therefore prone to errors. It would be better if it was similar to this one: https://github.com/MyGrades/mygrades-server/blob/master/database/seeds/universities/HSRMSeeder.php

Let me know if I can assist you with it. Alternatively, you could send me screens and source code (anonymised) from every page up to the table of grades and I'd update the rule.

**Comment by jonastheis** [comment]
Someone else sent me the source code and I was able to update it:
https://github.com/MyGrades/mygrades-server/commit/338ba82f19851bff495d41b3d406a0a474aef8aa
