### ISSUE TITLE
HSRM error

### ISSUE THREAD

**Issue by kaikilian** [MyGrades/mygrades-app#11]
HSRM Wiesbaden fetch grades fails.
Probably because now you need to log in to compass.hs-rm.de before you can access the qis portal.

**Comment by tilmanginzel** [comment]
Fixed in https://github.com/MyGrades/mygrades-server/commit/386d5b30c0e214e2de6528982aa0b3fe2fac4e0a. Please check if everything works again. :)

**Comment by kaikilian** [comment]
thanks, works again!
I noticed that you have to logout & login again, just for you to know.

**Comment by tilmanginzel** [comment]
That's great. 👍 We will keep the logout & login bug in mind. Some users confirmed that it worked immediately, others mentioned that a new login is required. Maybe it depends on whether you are currently stuck on the login screen, or if you are already fully logged in.
