### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by IzzySoft** [MyGrades/mygrades-app#12]
Just wondering: with no (visible) activity for almost 2 years, is this project still maintained?

**Comment by jonastheis** [comment]
We supported the [server component ](https://github.com/MyGrades/mygrades-server) until this year. However, we are currently in the process of shutting it down. Soon there will be an announcement regarding this.

**Comment by IzzySoft** [comment]
Thanks for the reply – even though it's sad news…

**Comment by DanielHabenicht** [comment]
Is there a way to continue this app? I would gladly step into your footsteps as this is something I used and still use.

**Comment by tilmanginzel** [comment]
Hey @DanielHabenicht,

that's great to hear! :)

There certainly are ways to continue this project, it is one of the reasons we fully open-sourced the app and [backend](https://github.com/MyGrades/mygrades-server). What kind of continuation do you have in mind? At first glance I can see two options:

1. We transfer ownership of the currently (un)published app and website to you and give you contributor rights on GitHub
2. You fork the project, publish a new app in the Play Store and host the backend on a new domain

Unfortunately 1. is not an option we are comfortable with for a few reasons [1]. Do you think 2. would be viable for you? We could help you along the way to set everything up. 

Is there a third option I am missing?

Cheers! :)

[1] We want to keep ownership of the domain `mygrades.de` for another couple of years even though the site and backend are offline. It mostly boils down to trust. The app is currently still installed on a couple of thousand devices. Handing over the domain to someone else adds a possible attack vector: The app is regularly trying to fetch rule updates for the university. The domain owner could overwrite the rules defined for the universities and redirect users before their login to a website in the attackers control. I am definitely not implying that you would ever do that, but handing over the domain is a no-go for us.

**Comment by IzzySoft** [comment]
I second your opinion, @tilmanginzel (and thanks for picking this up!). Another point against option 1 is again a "trust vector": even if here everything would be "kosher", for reasons based on precedents of some "big players" people get suspicious with "change of ownership". Starting a fork on the other side is completely transparent: nobody's "silently moved", no reason to complain (or suspect).

@DanielHabenicht and thanks to you for volunteering! I'm no user of the project, but I still wish you the very best. I hope you'll keep your fork FOSS; once you're there and have an app ready, be welcome to ping me if you want help with getting it into [F-Droid](https://f-droid.org/) (or [into my repo](https://apt.izzysoft.de/fdroid/index/apk/de.mygrades) if you prefer – which for F-Droid is something between testing, staging and non-free; disclosure: I'm one of the F-Droid maintainers).

**Comment by DanielHabenicht** [comment]
I think forking is also the best option. (I wouldn't trust a stranger as well). Maybe we can talk about transferring in the far future. 

Going Forward I will fork it to a new organization and release a new app. 
As I haven't found thorough documentation, can you point me to it or send me some details on how the app and backend in general works?
Especially build, release and hosting the backend are some points I am interested in. 
By the way which hosting provider did you use? Did you host the docker containers directly? 

I will keep you guys updated.

**Comment by DanielHabenicht** [comment]
If the server component is only serving the data for crawling the QIS-Pages, a simple static file host might be sufficient. <del>What is the reason for having a PHP-Backend </del> (and what is the user controller for)? 
Nevermind, it is the whole Website. 
Apart from that, just to make the App work serving the Functionality of `UniversityController` as static file should be enough?

**Comment by tilmanginzel** [comment]
> Going Forward I will fork it to a new organization and release a new app.

That is awesome and thanks for the effort! :)

> By the way which hosting provider did you use? Did you host the docker containers directly?

We hosted the backend on a $5 Digitalocean droplet and served it via nginx and docker containers. Some installation instructions for that can be found [here](https://github.com/MyGrades/mygrades-server#installation).

> As I haven't found thorough documentation, can you point me to it or send me some details on how the app and backend in general works?

Admittedly some relevant stuff (commands on how to seed the database or update universities) are not documented in the repositories, but I can send that to you. Please feel free to reach out via github@tilmanginzel.de or hallo@mygrades.de (this reaches both Jonas and me). It might also be easier to clarify some details directly via e.g. Telegram, Signal or else.

> If the server component is only serving the data for crawling the QIS-Pages, a simple static file host might be sufficient. What is the reason for having a PHP-Backend (and what is the user controller for)?

A major reason for the backend is that the QIS-Pages changed from time to time for certain universities. Not regularly, but it did happen a couple of times. Before the app starts the scraping process, it checks from the server if new scraping "rules" are available. This made updating and adding new universities a breeze, as we did not have to publish new app updates all the time. It also had other features like storing wishes and (manually send) error reports from users, and sending emails (to us).

> Apart from that, just to make the App work serving the Functionality of UniversityController as static file should be enough?

Yes if you want to keep it simple as a start, a static file host with all the rules (endpoints from `UniversityController`) would be good enough to scrape from the app.

> and what is the user controller for

`AuthController`? Huh, that seems to be a leftover from creating the Laravel project from scratch. To my knowledge it isn't used.

**Comment by DanielHabenicht** [comment]
Thanks for the information. 

> Admittedly some relevant stuff (commands on how to seed the database or update universities) are not documented in the repositories, but I can send that to you. Please feel free to reach out via github@tilmanginzel.de or hallo@mygrades.de (this reaches both Jonas and me). It might also be easier to clarify some details directly via e.g. Telegram, Signal or else.

I wrote you an email, with my contacts. You can send me the commands to the mail address as well. 

> A major reason for the backend is that the QIS-Pages changed from time to time for certain universities. Not regularly, but it did happen a couple of times. Before the app starts the scraping process, it checks from the server if new scraping "rules" are available. This made updating and adding new universities a breeze, as we did not have to publish new app updates all the time. It also had other features like storing wishes and (manually send) error reports from users, and sending emails (to us).

Get that. I might look into other ways of collecting feedback. But first I need the app up and running. 

>Yes if you want to keep it simple as a start, a static file host with all the rules (endpoints from UniversityController) would be good enough to scrape from the app.

Then this will be an easier way forward for me. Depending on how complicated the setup with the docker containers will be.

**Comment by DanielHabenicht** [comment]
Ok, the biggest step is almost done. 
The app is available as beta [here](https://play.google.com/store/apps/details?id=dh.mygrades) (but currently not working). The new update should be live in 1-7 days and then everything should be working. (except I still need a website and some webpages)

@IzzySoft how do I Integrate into your platform? 
@jonastheis @tilmanginzel should I prepare/is it ok if an in-app notification is shown that there is a new supported app available?

**Comment by IzzySoft** [comment]
@DanielHabenicht If you provide the APK file (ideally attached to `releases/`), my updater can grab it. If you want your app at f-droid.org, that's best started by filing an RFP (Request For Packaging). You could first start in my repo (so we already get an idea of what might need to be adapted to be accepted at f-droid.org, if anything), and start the RFP shortly thereafter – which is what hundreds of apps already did in the past :wink:

**Comment by tilmanginzel** [comment]
> @jonastheis @tilmanginzel should I prepare/is it ok if an in-app notification is shown that there is a new supported app available?

If I understand you correctly, I don't think that it is possible as we have unpublished our app a while ago from the Play Store. But we still sometimes receive emails asking us if the app is still maintained, I could happily redirect them to the new app. :)

**Comment by DanielHabenicht** [comment]
@IzzySoft I will add the APK to each release. Do I have to sign it additionally? 
The RFP might be blocked because I started to use firebase crashlytics. But maybe it will be accepted if I use [sentry.io](https://sentry.io)? 

@tilmanginzel that would be nice. The official release will be at the end of this week. 
I thought it would still be possible to modify the APK.

**Comment by IzzySoft** [comment]
@DanielHabenicht I don't know what you mean by "additionally", but it must be signed, yes. A single signature is sufficient :laughing:

As for Analytics: [ACRA](https://github.com/acra/ACRA) is accepted. I don't know about sentry.io (and your link results in an empty page).

**Comment by DanielHabenicht** [comment]
Well because I am using the "Manage the app signing key by the PlayStore" I am not sure if my upload signature is sufficient. 

Link is fixed, but Sentry is also open source. Acra is not an option for me because I don't want to host it but just use it.

**Comment by IzzySoft** [comment]
"Manage the app signing key by the PlayStore" is a bad idea. I know Google sells it differently, but it's essentially a lock-in (tying your app to them) and also allows them to manipulate your app. Choosing that path means to give away control. You could of course use a different signing key for the attached APK – but then you could also self-sign your apps for Play. I don't see any advantage with Google having the key.

As for Sentry: I cannot tell. It might at least rise the `Tracking` AntiFeature, and maybe also `NonFreeNet` (unless their service is also FLOSS and could be self-hosted – the latter [is true](https://docs.sentry.io/server/installation/), the former IMHO not; they use BSL-1.1, F-Droid only lists BSL-1.0 as OSI conform). Anyway, please make sure it's opt-in for your users, as it's essentially their data we're dealing with here. That would then also avoid the `Tracking` AntiFeature.

**Comment by DanielHabenicht** [comment]
> "Manage the app signing key by the PlayStore" is a bad idea. I know Google sells it differently, but it's essentially a lock-in (tying your app to them) and also allows them to manipulate your app. Choosing that path means to give away control. You could of course use a different signing key for the attached APK – but then you could also self-sign your apps for Play. I don't see any advantage with Google having the key.

Well, I already enrolled in it and I don't want to republish my app. So it will be a different signing key. 

> As for Sentry: I cannot tell. It might at least rise the `Tracking` AntiFeature, and maybe also `NonFreeNet` (unless their service is also FLOSS and could be self-hosted – the latter [is true](https://docs.sentry.io/server/installation/), the former IMHO not; they use BSL-1.1, F-Droid only lists BSL-1.0 as OSI conform). Anyway, please make sure it's opt-in for your users, as it's essentially their data we're dealing with here. That would then also avoid the `Tracking` AntiFeature.

That's what I had in mind. We will see what their process will flag. 
I will update you as I publish the first production release

**Comment by IzzySoft** [comment]
> Well, I already enrolled in it and I don't want to republish my app. So it will be a different signing key.

Not ideal, but I can understand your reasoning. Keep in mind that the longer you postpone it, the harder it will be to get out, though.

As in the end your app will hopefully be over at f-droid.org, it will have a different signature then anyway. Just remind me to include a note when listing it in my repo. Same for the opt-out – though I don't know what the lib you will use has as default: if that's opt-out, it will automatically trigger `Tracking`. Again, only for my repo.
