### ISSUE TITLE
Add Frankfurt University of Applied Sciences

### ISSUE THREAD

**Issue by boredland** [MyGrades/mygrades-app#2]
It uses QIS/LSF, so perhaps integrating it is not that hard.
https://his-www.dv.fh-frankfurt.de

**Comment by boredland** [comment]
Oh. Nevermind. Perhaps you should update the list of supported faculties in your PlayStore description.

**Comment by tilmanginzel** [comment]
Thanks for the hint! We updated the Play Store description, it should be online soon. ;)
