### ISSUE TITLE
Support for HftL

### ISSUE THREAD

**Issue by c0dr** [MyGrades/mygrades-app#5]
HftL uses QIS as well (https://qis.tel.hispro.de/qisserver/rds?state=user&type=0) so should be easy to integrate.

I might create a PR soon.

Edit: After looking a bit closer at the code I realized it's better to create the issue over at mygrades-server :grin: => Closing. Sorry.

**Comment by tilmanginzel** [comment]
Hey, no problem. Just create a new one at mygrades-server. 
The code you're probably looking for is [here](https://github.com/MyGrades/mygrades-server/tree/master/database/seeds/universities), there you can create a new file for the HftL. 

The repository is still missing some installation guides to test it properly, so if you need help, please reach out to tilman@mygrades.de

Thanks! :)
