### ISSUE TITLE
Publish APK on Github?

### ISSUE THREAD

**Issue by IzzySoft** [MyGrades/mygrades-app#7]
Would you mind to attach the `.apk` files to their corresponding `releases/`, so folks w/o Playstore access can grab them? Thanks in advance!

**Comment by tilmanginzel** [comment]
Yes, good idea, I updated the [latest release](https://github.com/MyGrades/mygrades-app/releases/tag/1.2.0)!

**Comment by IzzySoft** [comment]
Great! Thanks a lot! As a bonus, I put it in my repo, which can be used with the F-Droid client (see [here](https://apt.izzysoft.de/fdroid/index/apk/de.mygrades)). Updates are usually available within 24h of your attaching them to the new tag, so users would be informed of their availability and just had to tap the button :smile_cat:

**Comment by tilmanginzel** [comment]
Cool, thank you for that! Didn't know about custom F-Droid repos so far. I'll remember to attach the apk at future releases.

**Comment by IzzySoft** [comment]
There are lists [on F-Droid](https://f-droid.org/wiki/page/Known_Repositories) and [on my site](https://android.izzysoft.de/articles/named/list-of-fdroid-repos) if you want to see some more repos. Though most of them are keeping just a single app or a group of apps by the same dev or group (like Guardian project). My repo is the big exception: I'm collecting apps which are no longer maintained with F-Droid (mostly because of "non-free deps") or not available there as all, checking GH repos for them (which is how I found yours :smile_cat: ). Goal is to give another source to folks who cannot or do not want to use Google stuff (or other proprietary eco-systems) too much. Guess with currently over 220 apps (more than 10% the size of F-Droid's official repo), I'm doing not that bad :innocent:

**Comment by tilmanginzel** [comment]
Interesting, thanks for the information and doing that. :)

**Comment by IzzySoft** [comment]
You're welcome! Feel free to link it (next to the Playstore link) to spread the word :stuck_out_tongue_winking_eye:

**Comment by tilmanginzel** [comment]
Done.
